#!/bin/bash
var="$(lsblk -r | awk '/part/' | awk 'NF <= 6 {print}' | awk '{print "/dev/"$1 " (" $4 ")"}')"
srt="$(printf "${var}" | $HOME/scripts/rofi-dmenu "Mount?")"
out="$(printf "${srt}" | awk '{print $1}')"

loc="$(cat $HOME/scripts/.helper/mntloc | $HOME/scripts/rofi-dmenu "Where?")"
$HOME/scripts/prompt "Mount $out to $loc ?" "gksudo /sbin/mount $out $loc"
